version: '3.8'

services:
  backend:
    build: ./backend
    container_name: subscription-backend
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/database.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - subscription-network

  frontend:
    build: ./frontend
    container_name: subscription-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - subscription-network

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data

networks:
  subscription-network:
    driver: bridge